return {
  { "esmuellert/codediff.nvim", cmd = "CodeDiff", load_before = "neogit" },
  {
    "m00qek/baleia.nvim",
    load_before = "neogit",
    after = function() vim.g.baleia = require("baleia").setup {} end,
  },
  { "folke/snacks.nvim", load_before = "neogit" },
  {
    "NeogitOrg/neogit",
    cmd = "Neogit",
    ---@module "neogit"
    ---@type NeogitConfig
    opts = {
      disable_hint = true,
      graph_style = "kitty",
      log_pager = { "delta", "--width", "117" },
      use_default_keymaps = false,
      status = {
        mode_padding = 1,
        mode_text = {
          M = "",
          N = "",
          A = "",
          D = "",
          C = "",
          U = "",
          R = "󰗧",
          T = "󱁻",
          DD = "󰓁",
          AU = "󰓁",
          UD = "󰓁",
          UA = "󰓁",
          DU = "󰓁",
          AA = "󰓁",
          UU = "󰓁",
          ["?"] = "?",
        },
      },
      commit_editor = {
        staged_diff_split_kind = "auto",
      },
      signs = {
        hunk = { "", "" },
        item = { "", "" },
        section = { "", "" },
      },
      mappings = {
        commit_view = {
          ["a"] = "OpenFileInWorktree",
          ["o"] = "OpenCommitLinkInBrowser",
        },
        commit_editor = {
          ["q"] = "Close",
          ["<c-s>"] = "Submit",
          ["<c-c>"] = "Abort",
          ["<Up>"] = "PrevMessage",
          ["<Down>"] = "NextMessage",
        },
        commit_editor_I = {
          ["<c-s>"] = "Submit",
          ["<c-c>"] = "Abort",
        },
        rebase_editor = {
          ["p"] = "Pick",
          ["r"] = "Reword",
          ["e"] = "Edit",
          ["s"] = "Squash",
          ["f"] = "Fixup",
          ["x"] = "Execute",
          ["d"] = "Drop",
          ["b"] = "Break",
          ["q"] = "Close",
          ["<cr>"] = "OpenCommit",
          ["gk"] = "MoveUp",
          ["gj"] = "MoveDown",
          ["<c-c><c-c>"] = "Submit",
          ["<c-c><c-k>"] = "Abort",
          ["[c"] = "OpenOrScrollUp",
          ["]c"] = "OpenOrScrollDown",
        },
        rebase_editor_I = {
          ["<c-s>"] = "Submit",
          ["<c-c>"] = "Abort",
        },
        finder = {
          ["<cr>"] = "Select",
          ["<c-c>"] = "Close",
          ["<esc>"] = "Close",
          ["<c-n>"] = "Next",
          ["<c-p>"] = "Previous",
          ["<down>"] = "Next",
          ["<up>"] = "Previous",
          ["<tab>"] = "InsertCompletion",
          ["<c-y>"] = "CopySelection",
          ["<space>"] = "MultiselectToggleNext",
          ["<s-space>"] = "MultiselectTogglePrevious",
          ["<c-j>"] = "NOP",
          ["<ScrollWheelDown>"] = "ScrollWheelDown",
          ["<ScrollWheelUp>"] = "ScrollWheelUp",
          ["<ScrollWheelLeft>"] = "NOP",
          ["<ScrollWheelRight>"] = "NOP",
          ["<LeftMouse>"] = "MouseClick",
          ["<2-LeftMouse>"] = "NOP",
        },
        refs_view = {
          ["x"] = "DeleteBranch",
        },
        popup = {
          ["?"] = "HelpPopup",
          ["A"] = "CherryPickPopup",
          ["d"] = "DiffPopup",
          ["M"] = "RemotePopup",
          ["P"] = "PushPopup",
          ["X"] = "ResetPopup",
          ["Z"] = "StashPopup",
          ["i"] = "IgnorePopup",
          ["t"] = "TagPopup",
          ["b"] = "BranchPopup",
          ["B"] = "BisectPopup",
          ["w"] = "WorktreePopup",
          ["c"] = "CommitPopup",
          ["f"] = "FetchPopup",
          ["l"] = "LogPopup",
          ["^"] = "MarginPopup",
          ["m"] = "MergePopup",
          ["p"] = "PullPopup",
          ["r"] = "RebasePopup",
          ["v"] = "RevertPopup",
        },
        status = {
          ["j"] = "MoveDown",
          ["k"] = "MoveUp",
          ["o"] = "OpenTree",
          ["q"] = "Close",
          ["I"] = "InitRepo",
          ["1"] = "Depth1",
          ["2"] = "Depth2",
          ["3"] = "Depth3",
          ["4"] = "Depth4",
          ["Q"] = "Command",
          ["<tab>"] = "Toggle",
          ["za"] = "Toggle",
          ["zo"] = "OpenFold",
          ["zc"] = "CloseFold",
          ["zC"] = "Depth1",
          ["zO"] = "Depth4",
          ["x"] = "Discard",
          ["-"] = "Reverse",
          ["s"] = "Stage",
          ["S"] = "StageUnstaged",
          ["<c-s>"] = "StageAll",
          ["u"] = "Unstage",
          ["K"] = "Untrack",
          ["R"] = "Rename",
          ["U"] = "UnstageStaged",
          ["y"] = "ShowRefs",
          ["$"] = "CommandHistory",
          ["Y"] = "YankSelected",
          ["gp"] = "GoToParentRepo",
          ["<c-r>"] = "RefreshBuffer",
          ["<cr>"] = "GoToFile",
          ["<s-cr>"] = "PeekFile",
          ["<c-v>"] = "VSplitOpen",
          ["<c-x>"] = "SplitOpen",
          ["<c-t>"] = "TabOpen",
          ["{"] = "GoToPreviousHunkHeader",
          ["}"] = "GoToNextHunkHeader",
          ["[c"] = "OpenOrScrollUp",
          ["]c"] = "OpenOrScrollDown",
          ["<c-k>"] = "PeekUp",
          ["<c-j>"] = "PeekDown",
          ["<c-n>"] = "NextSection",
          ["<c-p>"] = "PreviousSection",
        },
      },
    },
    keys = {
      { "<Plug>(ConfigGit)", "<cmd>Neogit<cr>", desc = "Show Neogit UI" },
    },
  },
}
